# This is the workflow to manually deploy the bot to Google Cloud Functions

name: CI/CD Staging

on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    # The job runs on windows
    name: Deploy to Google Cloud Functions
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Prepare SDK for further steps
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.PROJECT_ID_STA }}
          service_account_key: ${{ secrets.GCLOUD_AUTH }}
          export_default_credentials: true

      - name: Activate Cloud Functions API
        run: gcloud services enable cloudfunctions.googleapis.com

      - name: Get Firebase credentials
        run: gsutil cp gs://keystorage-${{ secrets.PROJECT_ID_STA }}/credentials.json credentials.json

      - name: Deploy
        uses: google-github-actions/deploy-cloud-functions@v0.1.2
        with:
          name: mbs_bench_bot
          runtime: python37
          env_vars: LOG_SEVERITY=$LOG_LEVEL, BOT_TOKEN=$BOT_TOKEN, BOT_NAME=$BOT_NAME, ERROR_CHAT_ID=$ERROR_CHAT_ID, GOOGLE_CREDENTIALS=$GOOGLE_APPLICATION_CREDENTIALS
          region: europe-west1
          
        env:
          GOOGLE_APPLICATION_CREDENTIALS: "credentials.json"
          BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_API_KEY_STA }}
          BOT_NAME: "bench_bot_dev"
          LOG_LEVEL: "DEBUG"
          ERROR_CHAT_ID: ${{ secrets.ERROR_CHAT_ID }}